# 数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    我们的项目数据库是 onlinemall
    url: jdbc:mysql://127.0.0.1:3306/onlinemall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
#    设置你的数据密码
    password: 199811



  # 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
  mvc:
    format:
      date: yyyy-MM-dd
server:
  port: 8585
  servlet:
    encoding:
      charset: utf-8



# Mybatis 配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.demo.springboot.helloworld.mapper: debug
